# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: npm Install
      run: npm install
    - name: npm Build Angular
      run: npm build
    - name: Deploy to EC2 Instance
      uses: easingthemes/ssh-deploy@v4.1.0
      with: 
        ARGS: "-rlgoDzvc -i --delete"
        REMOTE_HOST: ${{secrets.REMOTE_HOST}}
        REMOTE_USER: ${{secrets.REMOTE_USER}}
        SSH_PRIVATE_KEY: ${{secrets.SSH_KEY}}
        TARGET: ${{secrets.TARGET}}
        SOURCE: ${{secrets.SOURCE}}
